# This workflow will generate/update a/the profile HTML page each time the 
# DDE genrates and update a JSON-LD in the _data/specifications folder (repo) 

name: generate-profile
  
on: [push]
jobs:
  generate-profile:
    runs-on: ubuntu-latest

    steps: 
      # Display the changed files
      
      - name: Checkout Spec Repo and Retreive the Preceding Commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v21

      - name: List Changed Files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      # Run the python script
      # Generate / Save the HTML profile in pages/_profiles

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "./.github/workflows/requirements.txt"

      - name: Execute the Python Script
        run: |
          python ./.github/workflows/conversion.py ${{steps.changed-files.outputs.all_changed_files}}

      - name: Checkout the Website repo
        env:
          GITHUB_TOKEN: ${{ secrets.Sahar_Workflows_Token }}
        run: | 
          git clone https://user:$GITHUB_TOKEN@github.com/BioSchemas/bioschemas.github.io
          ls

   #   - name: Checkout the Website repo
    #    uses: actions/checkout@v2
     #   with:
      #    repository: BioSchemas/bioschemas.github.io
       #   path: bioschemas.github.io

      # Commit and push the changes to the website
      - name: Setup the Github TOKEN
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          path: bioschemas.github.io
          email: sahar.frikha1@gmail.com
          name: sahar-frikha
          actor: sahar-frikha
          token: '${{secrets.Sahar_Workflows_Token}}'
      - name: Checkout the branch
        run: | 
          cd bioschemas.github.io
          git pull
          git checkout -b profile-auto-generation

      - name: Move the files to the website
        run: | 
          mv Profiles/ bioschemas.github.io
          cd bioschemas.github.io
          ls
          git status
      
      - name: Commit and Push the changes in the website
        run: | 
          cd bioschemas.github.io
          git checkout profile-auto-generation
          git pull
          git config user.name "sahar-frikha"
          git config user.email "sahar.frikha1@gmail.com"
          git add .
          git commit -m "Updating Profile"  # How to commit with a specific msg
          git push origin -f profile-auto-generation

      - name: End Workflow
        run: |
          echo "End Workflow!"