# This workflow will generate/update a/the profile HTML page each time the 
# DDE genrates and update a JSON-LD in the _data/specifications folder (repo) 

name: generate-profile
  
on: [push]
jobs:
  generate-profile:
    runs-on: ubuntu-latest

    steps: 
      # Display the changed files
      
      - name: Checkout Spec Repo and Retreive the Preceding Commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v21

      - name: List Changed Files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      # Run the python script
      # Generate / Save the HTML profile in pages/_profiles

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "./.github/workflows/requirements.txt"

      - name: Execute the Python Script
        run: |
          python ./.github/workflows/conversion.py ${{steps.changed-files.outputs.all_changed_files}}

      - name: Checkout the Website repo
        uses: actions/checkout@v2
        with:
          repository: BioSchemas/bioschemas.github.io
          ref: profile-auto-generation
          path: bioschemas.github.io

      - name: Move the files to the website
        run: | 
          mv Profiles/ /bioschemas.github.io/
          ls /bioschemas.github.io/

      # Commit and push the changes to the website
      - name: Setup the Github TOKEN
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          path: bioschemas.github.io
          token: '${{secrets.GITHUB_TOKEN}}'
      - name: Commit and Push
        run: | 
          cd ${{ github.workspace }}/bioschemas.github.io
          git status
          git add .
          git commit -m "Updating Profile"  # How to commit with a specific msg
          git push origin HEAD:profile-auto-generation  # Updated to master after the merge
      - name: End Workflow
        run: |
          echo "End Workflow!"