name: Trigger bioschemas.github.io Workflow
on: [push]
jobs:
  build:
    name: Fire the "auto-generate-profile" Action
    runs-on: ubuntu-latest
    steps:
      - name: Wait 5s
        run: |
          echo "Wait 5s,so that workflows do not overlap"
          sleep 5s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: BioSchemas
          repo: bioschemas.github.io
          github_token: ${{ secrets.Sahar_Workflows_Token }}
          workflow_file_name: generate_profile_workflow.yml
          ref: profile-auto-generation
      - name: Done! 
        run: |
          echo "Done! Check bioschemas.github.io Repo "